app/security_ui/forms.py
from flask import flash
from flask_wtf import FlaskForm
from wtforms import (
    IntegerField,
    StringField,
    RadioField,
    PasswordField,
    TextAreaField,
    HiddenField,
    BooleanField,
)
from wtforms.validators import Length, DataRequired


class FlashingForm(FlaskForm):
    def validate_on_submit(self):
        result = super(FlashingForm, self).validate_on_submit()

        if not result:
            for field, errors in self.errors.items():
                for error in errors:
                    flash(
                        "Error in the {} field - {}".format(
                            getattr(self, field).label.text, error
                        ),
                        "error",
                    )
        return result


class LoginForm(FlashingForm):
    username = StringField("UHL Username", validators=[Length(max=100)])
    password = PasswordField("UHL Password", validators=[Length(max=50)])

app/ui/forms.py
from flask import flash
from flask_wtf import FlaskForm
from wtforms import (
    IntegerField,
    StringField,
    TextAreaField,
    HiddenField,
    SelectField,
    BooleanField,
)
from wtforms.validators import Length, DataRequired
from flask_wtf.file import FileField as _FileField, FileAllowed, FileRequired
from wtforms.widgets import FileInput as _FileInput


class FlashingForm(FlaskForm):
    def validate_on_submit(self):
        result = super(FlashingForm, self).validate_on_submit()

        if not result:
            for field, errors in self.errors.items():
                for error in errors:
                    flash(
                        "Error in the {} field - {}".format(
                            getattr(self, field).label.text, error
                        ),
                        "error",
                    )
        return result


class FileInput(_FileInput):

    def __call__(self, field, **kwargs):
        if field.accept:
            kwargs[u'accept'] = ','.join(field.accept)
        return _FileInput.__call__(self, field, **kwargs)


class FileField(_FileField):
    widget = FileInput()

    def __init__(self, *args, **kwargs):
        self.accept = kwargs.pop('accept', None)
        super(FileField, self).__init__(*args, **kwargs)


class SearchForm(FlashingForm):
    search = StringField("Search", validators=[Length(max=20)])
    page = IntegerField("Page", default=1)


class ConfirmForm(FlashingForm):
    id = HiddenField("id", validators=[DataRequired()])


class BankUploadForm(FlashingForm):
    name = StringField("Name", validators=[Length(max=50)])
    upload = FileField(
        'Bank Wave File',
        accept=['audio/wav'],
        validators=[FileRequired()]
    )


app.py
#!/usr/bin/env python3

from dotenv import load_dotenv

# Load environment variables from '.env' file.
load_dotenv()

from app import create_app

application = create_app()

if __name__ == "__main__":
    application.run(host="0.0.0.0", port=8000)

app/__init__.py
import os
import logging
from flask import Flask
from .ui import blueprint as ui_blueprint
from .security_ui import blueprint as security_blueprint
from .database import db
from .template_filters import init_template_filters
from .standard_views import init_standard_views
from .utils import ReverseProxied
from .config import BaseConfig
from .admin import init_admin


def create_app(config=BaseConfig):
    app = Flask(__name__)
    app.wsgi_app = ReverseProxied(app.wsgi_app)
    app.config.from_object(config)
    app.config.from_pyfile("application.cfg", silent=True)

    with app.app_context():
        app.logger.setLevel(logging.INFO)
        db.init_app(app)
        init_template_filters(app)
        init_standard_views(app)
        init_admin(app)

    app.register_blueprint(ui_blueprint)
    app.register_blueprint(security_blueprint)

    return app

app/security_ui/__init__.py
import time
import logging
from urllib.parse import urlparse, urljoin
from flask import (
    Blueprint,
    render_template,
    redirect,
    abort,
    url_for,
    flash,
    request,
    current_app,
)
from flask_login import (
    LoginManager,
    login_user,
    logout_user,
    current_user,
)
from .forms import LoginForm
from ..database import db
from .model import User, validate_password


blueprint = Blueprint("security_ui", __name__, template_folder="templates")
login_manager = LoginManager()


@login_manager.user_loader
def load_user(username):
    return User.query.filter_by(username=username).one_or_none()


@blueprint.record
def record(state):
    if db is None:
        raise Exception(
            "This blueprint expects you to provide database access through database"
        )
    
    login_manager.init_app(state.app)
    login_manager.login_view = "security_ui.login"

    @state.app.before_first_request
    def init_data():
        _init_users()


def _init_users():
    if User.query.filter_by(username=current_app.config['ADMIN_USER_USERNAME']).count() == 0:
        admin = User(
            username=current_app.config['ADMIN_USER_USERNAME'],
            first_name=current_app.config['ADMIN_USER_FIRST_NAME'],
            last_name=current_app.config['ADMIN_USER_LAST_NAME'],
        )
        db.session.add(admin)

    db.session.commit()


def _login(username, password):
    current_app.logger.info('Username supplied for login: %s', username)

    user = User.query.filter_by(username=username).first()

    current_app.logger.info('User attempting log in: %s', user)

    if user:
        if user.is_active:
            if validate_password(user, password):
                login_user(user)
                current_app.logger.info('User logged in: %s', user.username)
                return user
    
    time.sleep(2)


def is_safe_url(target):
    ref_url = urlparse(request.host_url)
    test_url = urlparse(urljoin(request.host_url, target))
    return test_url.scheme in ('http', 'https') and \
           ref_url.netloc == test_url.netloc


@blueprint.route("/login",methods=["GET", "POST"])
def login():
    next_url = request.args.get('next')
    if not is_safe_url(next_url):
        return abort(400)

    if current_user.is_authenticated:
        return redirect(next_url or url_for('ui.index'))

    form = LoginForm()

    if form.validate_on_submit():
        user = _login(form.username.data, form.password.data)

        current_app.logger.info('Logged in user: %s', user)

        return redirect(next_url or url_for('ui.index'))

    return render_template('login.html', form=form, next_url=next_url)


@blueprint.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('ui.index'))

app/ui/__init__.py
from flask import Blueprint
from ..database import db


blueprint = Blueprint("ui", __name__, template_folder="templates")

# Login required for all views
@blueprint.before_request
def before_request():
    pass


@blueprint.record
def record(state):
    if db is None:
        raise Exception(
            "This blueprint expects you to provide " "database access through database"
        )

from .views import *

app/ui/views/__init__.py
__all__ = [
    "home",
]

app/ui/views/home.py
from flask import render_template, redirect, url_for, current_app
from .. import blueprint
from app.model import Application


@blueprint.route("/")
def index():
    applications = Application.query.order_by(Application.name).all()

    return render_template("index.html", applications=applications)


@blueprint.route("/security_statement/<int:id>")
def security_statement(id):
    application = Application.query.get_or_404(id)

    return render_template("security_statement.html", application=application)


@blueprint.route("/security_statement/text/<int:id>")
def security_statement_text(id):
    application = Application.query.get_or_404(id)

    return '\n\n'.join([
        application.application_type.statement,
        application.hosting.statement,
        application.authentication.statement,
        application.visibility.statement,
    ])

app/security_ui/templates/_loginFormBase.html
{% extends "_subbase.html" %}
{% import "_errors.html" as errors %}


{% block base_content %}

<div class="row h-100 justify-content-center">
  <div class="login-form">  
    {{ errors.render() }}
    <div class="card">
      <div class="card-header">
          <div>{{ config.SITE_NAME }}: {% block formname %}{% endblock %}</div>
      </div>

      <div class="card-body">
          {% block content %}{% endblock %}
      </div>
    </div>
  </div>

</div>  

{% endblock %}

app/security_ui/templates/login.html
{% extends "_loginFormBase.html" %}
{% import "_formHelpers.html" as formhelper %}

{% block formname %}Login{% endblock%}
{% block errors %}
	{{ formhelper.render_form_errors(login_user_form)  }}
{% endblock %}

{% block content %}

<form action="{{ url_for('security_ui.login', next=next_url) }}" method="POST" name="login_user_form">
	{{ form.hidden_tag() }}

	<div class="form-group input-group">
		<span class="input-group-prepend" id="basic-addon1">
			<span class="input-group-text">
				<span class="fas fa-user"></span>
			</span>
		</span>
		{{ form.username(class="form-control", placeholder="UHL Username") }}
	</div>

	<div class="form-group input-group">
		<span class="input-group-prepend" id="basic-addon1">
			<span class="input-group-text">
				<span class="fas fa-lock"></span>
			</span>
		</span>
		{{ form.password(class="form-control", placeholder="UHL Password") }}
	</div>

	<div class="text-right">
		<button type="submit" class="btn btn-primary">Login</button>
	</div>
</form>
{% endblock %}

app/templates/_base.html
{% extends "_subbase.html" %}
{% import "_errors.html" as errors %}

{% set home_class = 'active' %}

{% block base_content %}

<div id="main-wrapper">

  <header class="pageheader">
    <div class="container">
      <h1>{{ config.SITE_NAME }}</h1>
    </div>
  </header>

  <div class="container">
    <nav class="navbar navbar-expand-sm">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a class="navbar-brand fas fa-home" href="{{ url_for('ui.index') }}"></a>
        </li>
      </ul>

      <ul class="navbar-nav ml-auto">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Admin</a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="{{ url_for('security_ui.login', next=url_for('admin.index'))}}">Maintenance</a>
          </div>
        </li>

        {% if current_user.is_active %}
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">{{ current_user.full_name }}</a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="{{ url_for('security_ui.logout') }}">Log Out</a>
            </div>
          </li>
        {% endif %}
      </ul>    
  </nav>
  </div>

  <div class="container">
      {{ errors.render() }}
      {% block errors %}{% endblock %}
  </div>
        
  <div id="content" class="container">
    {% block content %}{% endblock %}
  </div>

  <footer>
    <div class="container">
        Copyright &copy; {{ current_year }} NIHR Leicester Biomedical Research Centre
    </div>
  </footer>

</div>
{% endblock %}

app/templates/_errors.html
{% macro render() %}

<div class="errors">
    {% with messages = get_flashed_messages(with_categories=true) %}
    {% for category, message in messages %}

        {% set class="alert-info" %}
        {% set fas_class="fa-comment" %}

        {% if category == "warning" %}
        {% set class="alert-warning" %}
        {% set fas_class="fa-exclamation" %}
        {% elif category == "error" %}
        {% set class="alert-danger" %}
        {% set fas_class="fa-exclamation" %}
        {% elif category == "success" %}
        {% set class="alert-success" %}
        {% set fas_class="fa-check" %}
        {% endif %}


        <div class="row  justify-content-center">
            <div class="alert {{class}}" role="alert">
                <i class="fas {{fas_class}}"></i>
                <span class="sr-only">{{category}}:</span>
                {{message}}
            </div>
        </div>
    {% endfor %}
    {% endwith %}

    {% block errors %}{% endblock %}
</div>  
{% endmacro %}

app/templates/_formHelpers.html
{% macro render_field(field, label=None) %}
  <div class="row">
    <div class="form-group{% if field.errors %} has-error{%endif%} col-md-12">
        {% if field.type == "HiddenField" or field.type == "CSRFTokenField" %}
        {% elif field.type == "BooleanField" %}
            {{ field.label(class="control-label", text=label) }}{{ render_checkbox_field_control(field, **kwargs) }}
        {% elif field.type == "RadioField" %}
            {{ field.label(class="control-label", text=label) }}{{ render_radio_field_control(field, **kwargs) }}
        {% else %}
            {{ field.label(class="control-label", text=label) }}{{ render_field_control(field, **kwargs) }}
        {% endif %}
    </div>
  </div>
{% endmacro %}


{% macro render_checkbox_field_control(field) %}
    {{ field(class="checkbox", **kwargs)|safe }}
{% endmacro %}


{% macro render_radio_field_control(field) %}
    {{ field(class="radio", **kwargs)|safe }}
{% endmacro %}


{% macro render_field_control(field) %}
    {{ field(class="form-control", **kwargs)|safe }}
{% endmacro %}


{% macro render_button_bar(cancelview, submit_label="Save", cancelviewparams={}, modal_cancel=False) %}
      <div class="form-group text-right">
          <div>
              {% if cancelview %}
                <a href="{{ url_for(cancelview, **cancelviewparams) }}" class="btn btn-default" role="button">Cancel</a>
              {% endif %}
              {% if modal_cancel %}
                <a class="btn btn-default" data-dismiss="modal" aria-label="Close" role="button">Cancel</a>
              {% endif %}
              <button type="submit" class="btn btn-primary">{{ submit_label }}</button>
          </div>
      </div>
{% endmacro %}

{% macro render_form(form, submit_label) %}
  {{ form.hidden_tag() }}

  {% for field in form %}
    {{ render_field(field) }}
  {% endfor %}
{% endmacro %}


{% macro render_form_errors(form) %}
    {% for field in form %}
      {% if field.errors %}
        <div class="alert alert-dismissible alert-danger">
            <button type="button" class="close" data-dismiss="alert">×</button>
            <p>{{ field.label }} has the following errors:</p>
            <ul>
            {% for error in field.errors%}
                <li>{{ error }}</li>
            {% endfor %}
            </ul>
          </div>
      {% endif %}
    {% endfor %}

{% endmacro %}


{% macro render_search(searchForm, searchview, placeholder='enter search text', buttons={}, checkboxes={}) %}
<form method="GET" class="form-horizontal" action="{{ url_for(searchview, **kwargs) }}">

  <div class="input-group">
    {{ searchForm.search(class="form-control", placeholder=placeholder) | safe }}
    {% for field in searchForm %}
      {% if field.type == "BooleanField" %}
        <div class="input-group-append">
          <div class="input-group-text">
            {{ field(**kwargs)|safe }}
            {{ field.label.text }}
          </div>
        </div>
        {% endif %}
    {% endfor %}

    <div class="input-group-append">
      {% for key, value in buttons.items() %}
        <span class="input-group-text">
          <a href="{{ url_for(value, **kwargs) }}">{{ key }}</a>
        </span>
      {% endfor %}
      <span class="input-group-text">
          <a href="{{ url_for(searchview, **kwargs) }}">Clear Search</a>
      </span>
    </div>
    <div class="input-group-append">
      <button type="submit" class="btn btn-primary">Search</button>
    </div>
  </div>

  {% if searchForm | rejectattr("type", "ne", "SelectField") | list | length is ge(1) %}
    <div class="search-filters">
      <div class="row">
        {% for field in searchForm | rejectattr("type", "ne", "SelectField") %}
          <div class="form-group{% if field.errors %} has-error{%endif%} col">
            <div>{{ field.label.text | nbsp}}</div>
            <div>{{ field(**kwargs)|safe }}</div>
          </div>
        {% endfor %}
      </div>
    </div>
  {% endif %}

</form>
{% endmacro %}


{% macro render_pagination(pagination, endpoint, form) %}
  {% if pagination.pages > 1 %}

  {% for f in form | rejectattr("name", "eq", "page") | rejectattr("name", "eq", "csrf_token") | selectattr("data") %}
    {% if kwargs.update({f.name: f.data}) %} {% endif %}
  {% endfor %}

  <ul class="pagination">
    {% if pagination.has_prev %}
      <li class="page-item"><a class="page-link" href="{{ url_for(endpoint, page=pagination.prev_num, **kwargs) }}" rel="prev">Previous</a></li>
    {% else %}
      <li class="page-item disabled"><a class="page-link">Previous</a></li>
    {% endif %}

    {%- for page in pagination.iter_pages(left_edge=1, left_current=2, right_current=3, right_edge=1) %}
      {% if page %}
        {% if page != pagination.page %}
          <li class="page-item"><a class="page-link" href="{{ url_for(endpoint, page=page, **kwargs) }}">{{ page }}</a></li>
        {% else %}
          <li class="page-item active"><a class="page-link">{{ page }}</a></li>
        {% endif %}
      {% else %}
        <li class="page-item disabled"><a class="page-link">…</a></li>
      {% endif %}
    {%- endfor %}

    {% if pagination.has_next %}
      <li class="page-item"><a class="page-link" href="{{ url_for(endpoint, page=pagination.next_num, **kwargs) }}" rel="next">Next</a></li>
    {% else %}
      <li class="page-item disabled"><a class="page-link">Next</a></li>
    {% endif %}
    </ul>
  {% endif %}
{% endmacro %}

app/templates/_subbase.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta charset="utf-8">
    <title>{{ config.SITE_NAME }}</title>
    <!-- meta -->
    <meta name="description" content="">
    <meta name="author" content="Richard Bramley">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    
    <!-- Fonts -->
    <link rel='stylesheet' id='megamenu-google-fonts-css'  href='//fonts.googleapis.com/css?family=Lato%3A400%2C700&#038;ver=5.2.4' type='text/css' media='all' />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.css" crossorigin="anonymous">
    
    <!-- styles -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
    <link href="{{ url_for('static', filename='css/brc.css', ver=1) }}" rel="stylesheet">

    {% block css %}{% endblock %}

    <link rel="icon" href="{{ url_for('static', filename='img/cropped-favicon-32x32.png') }}" sizes="32x32" />
    <link rel="icon" href="{{ url_for('static', filename='img/cropped-favicon-192x192.png') }}" sizes="192x192" />
    <link rel="apple-touch-icon-precomposed" href="{{ url_for('static', filename='img/cropped-favicon-180x180.png') }}" />
    <meta name="msapplication-TileImage" content="{{ url_for('static', filename='img/cropped-favicon-270x270.png') }}" />
    
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv-printshiv.js"></script>
      <script src="//cdnjs.cloudflare.com/ajax/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    {% block base_content %}{% endblock %}

    <!-- scripts -->
    <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    {% block js %}{% endblock %}

  </body>
</html>

app/ui/templates/index.html
{% extends "_base.html" %}

{% block content %}
<section>
    <h2>Applications</h2>

    <div class="row">
        <div class="col">
            <ul class="list-group">
                {% for a in applications %}
                    <li class="list-group-item">
                        <header class="float-left">
                            <h1>{{ a.name }}</h1>
                        </header>

                        <a class="float-right btn btn-secondary" href="{{ url_for('ui.security_statement', id=a.id) }}">Security Statement</a>
                        <a class="float-right btn btn-secondary" href="{{ url_for('ui.index') }}">DPIA</a>
                    </li>
                {% endfor %}
            </ul>
        </div>
    </div>

</section>
{% endblock %}

app/ui/templates/security_statement.html
{% extends "_base.html" %}

{% block content %}
<section>
    <h2>{{ application.name}} Security Statement</h2>

    <p class="statement">{{ application.application_type.statement }}</p>
    <p class="statement">{{ application.hosting.statement }}</p>
    <p class="statement">{{ application.authentication.statement }}</p>
    <p class="statement">{{ application.visibility.statement }}</p>

</section>
{% endblock %}